/** dsh-theme-tone 入口：host half 契约 + 供单测引用的纯逻辑表面。 */
export { apply, inject, name } from './host.js'
export {
  BACKDROP_SELECTOR,
  LAYER_SELECTOR,
  STYLE_SELECTOR,
  buildBackdropCss,
  backdropPlan,
  tonePreview,
  boostAlpha,
  GRAIN_DATA_URI,
  GRAIN_OPACITY,
  PREVIEW_ALPHA_SCALE,
  REQUIRED_CSS_FEATURES,
  type BackdropPlan,
} from './backdrop.js'
export {
  BOTTOM_VARIABLE,
  GRAIN_ATTR,
  GRAIN_TILE_VARIABLE,
  LEFT_VARIABLE,
  MARKER_ATTR,
  PANEL_VARIABLE,
  PLAIN_ATTR,
  POPUP_BOTTOM_SHAPE,
  POPUP_GRAIN_DATA_URI,
  POPUP_STOP,
  POPUP_TOP_SHAPE,
  TOP_VARIABLE,
} from './constants.js'
export {
  BORDER_TOKENS,
  DARK_TONES,
  DEFAULT_SETTINGS,
  DEPTH_ALPHA,
  LIGHT_GLOW_ALPHA,
  LIGHT_TOKENS,
  LIGHT_TONES,
  PANEL_TINT,
  POPUP_TOKENS,
  SCROLLBAR_TOKENS,
  STATE_TOKENS,
  SURFACE_RUNGS,
  SURFACE_TINT,
  SURFACE_TOKENS,
  TOP_STOP,
  WASH_TINT,
  WASH_TOKENS,
  availableToneIds,
  panelFill,
  toneFieldFor,
  toneFor,
  toneIdOf,
  toneIdsFor,
  tokenOverrides,
  washFill,
  type SurfaceRung,
  type ThemeToneSettings,
  type ToneId,
  type ToneSpec,
} from './tones.js'
export { ThemeToneSettingsSchema } from './settings-schema.js'
export {
  GLASS_BLUR,
  GLASS_CARD_ALPHA,
  GLASS_CARD_BLUR,
  GLASS_CARD_LIFT,
  GLASS_CARD_PHASES,
  GLASS_HEADER_ALPHA,
  HEADER_HEIGHT_PX,
  SEAT_SOLID_PX,
  SEAT_SOLID_RAMP_PX,
  SEAM_NOTCH_PX,
  buildGlassCss,
  buildSeamCss,
  phaseGate,
} from './glass.js'
export {
  COMPOSER_CARD_ANCHORS,
  COMPOSER_ICON_BUTTON_SCOPE,
  GROUPED_MENU_SELECTOR,
  GROUPED_MENU_TITLE_SELECTOR,
  SURFACE_ANCHORS,
  buildSurfaceCss,
  menuSurfaceLayers,
  surfaceLayers,
} from './surface.js'
export {
  SWEEP_ANCHORS,
  SWEEP_PLATE_ALPHA,
  SWEEP_PLATE_LAYERS,
  SWEEP_SHAPE_MASK,
  buildSweepCss,
} from './sweep.js'

